@startuml ArchitectureSequence
skinparam style strictuml
actor User

participant ":UI" as UI
participant ":App" as App
participant ":Parser" as Parser
participant ":DeleteCommand" as DeleteCommand
participant ":StudentDatabase" as Model
participant ":Storage" as Storage

User -> UI : "delete 1"
activate UI
UI -> App : readCommand()
activate App
App -> Parser : parse("delete 1")
activate Parser
Parser -> DeleteCommand ** : create
activate DeleteCommand
DeleteCommand --> Parser
deactivate DeleteCommand
Parser -->> App : deleteCommand
deactivate Parser

App -> DeleteCommand : execute(db, storage)
activate DeleteCommand
DeleteCommand -> Model : removeStudent(0)
activate Model
Model -->> DeleteCommand : deletedStudent
deactivate Model

DeleteCommand -> Storage : saveStudentList(db)
activate Storage
Storage -->> DeleteCommand
deactivate Storage

DeleteCommand -->> App : commandResult
deactivate DeleteCommand

App -> UI : show(result.getMessage())
UI --> User : display result
deactivate App
deactivate UI
@enduml
