@startuml ArchitectureDiagram
skinparam style strictuml
skinparam defaultFontSize 13
skinparam componentStyle rectangle

skinparam component {
    BorderColor #444444
    BackgroundColor #FFFFFF
    FontStyle bold
}

skinparam rectangle {
    BorderColor #444444
    BackgroundColor #FFFFFF
}

actor User

component [UI] as UI
component [App] as App
component [Parser] as Parser
component [Model] as Model
component [Storage] as Storage

rectangle "  Main  " as Main

User --> UI : uses

Main ..> UI      : creates
Main ..> Parser  : creates
Main ..> Storage : creates
Main ..> Model   : creates
Main ..> App     : creates & runs

App --> UI      : uses
App --> Parser  : uses
App --> Model   : uses
App --> Storage : uses
Parser ..> Model : creates Commands
Storage --> Model : uses

note right of Storage
  Reads/writes
  DextroStudentList.txt
end note

@enduml
