@startuml ArchitectureDiagram

skinparam componentStyle rectangle
skinparam defaultFontSize 13
skinparam ArrowThickness 1.5


actor User


[Commons\n(Config · Exceptions)] <<Commons>> as Commons

database "DextroStudentList.txt" as DataFile

User      ..>  [UI]      : input / output

[UI]      -->  [Parser]  : raw input
[Parser]  -->  [Model]   : reads / mutates
[Parser]  -->  [Storage] : saves
[Model]   -->  [UI]      : result

[Main]    ..>  [UI]      : creates
[Main]    -->  [Model]   : creates & loads
[Main]    ..>  [Storage] : creates

[Storage] ..>  DataFile  : reads / writes

[UI]      -->  Commons   : uses
[Parser]  -->  Commons   : uses

@enduml
