@startuml
skinparam style strictuml
actor User

participant ":App" as App
participant ":Parser" as Parser
participant ":StatusCommand" as Status
participant ":StudentDatabase" as DB
participant ":Student" as Student
participant ":Ui" as Ui

title StatusCommand - Sequence Diagram

User -> App : "status 1"
activate App
App -> Parser : parse(input)
activate Parser
Parser -> Status ** : create(1)
activate Status
Status -->> Parser
deactivate Status
Parser -->> App : command
deactivate Parser
App -> Status : execute(db, storage)
activate Status
Status -> DB : getStudent(0)
activate DB
DB -->> Status : student
deactivate DB
Status -> Student : calculateCap()
activate Student
Student -->> Status : cap
deactivate Student
Status -> Student : getTotalMCs()
activate Student
Student -->> Status : totalMCs
deactivate Student
Status -> Student : getProgressStatus()
activate Student
Student -->> Status : status
deactivate Student
Status -->> App : commandResult(formatted status)
deactivate Status
App -> Ui : show(result.getMessage())
activate Ui
Ui -->> User : display status
deactivate Ui
deactivate App
@enduml